### ISSUE TITLE
A .table-striped inside a .card ignores border-radius on odd rows

### ISSUE THREAD

**Issue by casually-creative** [adminkit/adminkit#126]
## Current Behavior 😯

When you put a .table-striped inside a .card, and you have an odd row at the top or bottom, the top or bottom border radius respectively of the card gets ignored. Giving you a sharp corner.

## Expected Behavior 🤔

The card keeps its border radius.

## Steps to Reproduce 🕹

Most basic:

```html
<div class="card">
    <table class="table table-striped">
        <tbody>
            <tr><td>Something 1</td></tr>
            <tr><td>Something 2</td></tr>
        </tbody>
    </table>
</div>
```

## Your Environment 🌎

- Browser: Chrome 102.0.5005.63
- OS: Windows 10
- Screen size: no impact

## Screenshots 📷

The phenomenon can be seen on the adminkit live demo page (Striped Rows section: https://demo.adminkit.io/tables-bootstrap.html
Here is a gif of the demo page (look at bottom radiuses): 
![adminkit-card-table-border-bug](https://user-images.githubusercontent.com/5587999/170875705-3e91541a-fb49-41a1-b582-2838d7bb7b97.gif)

For me it looks like this (look at top radiuses):

![image](https://user-images.githubusercontent.com/5587999/170876196-0dca4f48-f865-4994-a5f4-2a0530122ed8.png)

**Comment by casually-creative** [comment]
Currently fixed it with custom scss:

```scss
.card
{
    & > table,
    & > .table
    {
        overflow: hidden;
        border-radius: inherit;
    }
}```

Looking for an official fix in the kit though.

**Comment by paullaros** [comment]
Thanks! We came up with the following solution, which will be part of the next version of AdminKit:

```scss
.card > .table > tbody {
  tr:last-child td:first-child,
  tr:last-child th:first-child {
    border-bottom-left-radius: $card-border-radius;
  }
  tr:last-child td:last-child,
  tr:last-child th:last-child {
    border-bottom-right-radius: $card-border-radius;
  }
}
```
